In [2]:
import pandas as pd
import numpy as np

In [3]:
dados = "https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv"

df = pd.read_csv(dados, sep= ";", encoding= "latin1")
display(df.head()) # Exibe as primeiras linhas do DataFrame para verificar os dados ou #df.head() para o mesmo resultado.

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [4]:
df.tail()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,2.0,0.0,37,1,0,0,0,0,157,2
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,32,0,0,0,0,0,234,2
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,10.0,0.0,98,9,1,0,0,0,713,2
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,3.0,0.0,25,2,0,0,0,0,258,2
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0.0,0.0,3,0,0,0,0,0,57,2

In [5]:
df_furto_celular_cisp = df.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_celular_cisp

     cisp  furto_celular
0       1          15487
1       4          13700
2       5          23969
3       6           6410
4       7           1485
..    ...            ...
133   159            455
134   165           1233
135   166           2580
136   167            497
137   168            121

[138 rows x 2 columns]

In [6]:
df.describe()

,cisp,mes,ano,aisp,risp,mcirc,hom_doloso,lesao_corp_morte,latrocinio,cvli,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
count,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,3.731400e+04,37314.000000,37314.000000,37314.000000,37314.000000,...,32668.000000,32668.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000
mean,81.724259,6.482232,2014.188723,20.148470,3.869942,3.791939e+06,2.925256,0.028140,0.095380,3.048775,...,8.741306,0.641545,41.308731,3.223964,0.360481,0.022967,0.013400,0.002224,444.005306,2.985314
std,48.320410,3.461767,6.625316,11.348509,2.011450,1.741132e+06,4.327953,0.179516,0.366265,4.443058,...,14.809300,1.640367,39.390699,4.160668,0.988235,0.181215,0.130895,0.049334,398.542615,0.120295
min,1.000000,1.000000,2003.000000,1.000000,1.000000,3.300100e+06,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,38.000000,3.000000,2008.000000,10.000000,2.000000,3.302601e+06,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,106.000000,3.000000
50%,78.000000,6.000000,2014.000000,20.000000,4.000000,3.304557e+06,1.000000,0.000000,0.000000,1.000000,...,5.000000,0.000000,30.000000,2.000000,0.000000,0.000000,0.000000,0.000000,370.000000,3.000000
75%,125.000000,9.000000,2020.000000,30.000000,6.000000,3.304557e+06,4.000000,0.000000,0.000000,4.000000,...,11.000000,1.000000,56.000000,5.000000,0.000000,0.000000,0.000000,0.000000,663.000000,3.000000
max,168.000000,12.000000,2026.000000,43.000000,7.000000,9.999999e+06,43.000000,6.000000,9.000000,43.000000,...,419.000000,60.000000,370.000000,191.000000,112.000000,10.000000,4.000000,2.000000,3185.000000,3.000000

In [7]:
df.shape

(37314, 65)

In [8]:
df.iloc[0:5]

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [9]:
df_rj = df.loc[df["munic"] == "Rio de Janeiro"]
df_rj

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37213,40,1,2026,2026m01,9,2,Rio de Janeiro,3304557,Capital,3,...,3.0,2.0,38,5,1,0,0,0,689,2
37214,41,1,2026,2026m01,18,2,Rio de Janeiro,3304557,Capital,2,...,5.0,0.0,37,3,1,0,0,0,858,2
37215,42,1,2026,2026m01,31,2,Rio de Janeiro,3304557,Capital,2,...,15.0,6.0,113,7,0,0,0,0,1444,2
37216,43,1,2026,2026m01,27,2,Rio de Janeiro,3304557,Capital,0,...,3.0,0.0,103,11,0,0,0,0,645,2
37217,44,1,2026,2026m01,3,1,Rio de Janeiro,3304557,Capital,1,...,12.0,0.0,32,3,0,0,0,0,853,2

In [10]:
df_2024 = df.loc[df["ano"] == 2024]
df_2024

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
33889,1,1,2024,2024m01,5,1,Rio de Janeiro,3304557,Capital,0,...,16.0,4.0,12,0,0,0,0,0,889,3
33890,4,1,2024,2024m01,5,1,Rio de Janeiro,3304557,Capital,0,...,8.0,6.0,13,3,0,0,0,0,728,3
33891,5,1,2024,2024m01,5,1,Rio de Janeiro,3304557,Capital,0,...,12.0,2.0,46,3,0,0,0,0,1441,3
33892,6,1,2024,2024m01,4,1,Rio de Janeiro,3304557,Capital,0,...,2.0,1.0,23,2,0,0,0,0,650,3
33893,7,1,2024,2024m01,5,1,Rio de Janeiro,3304557,Capital,0,...,0.0,0.0,12,2,0,0,0,0,240,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35528,159,12,2024,2024m12,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,1.0,0.0,27,2,0,0,0,0,137,3
35529,165,12,2024,2024m12,33,5,Mangaratiba,3302601,Interior,1,...,6.0,0.0,31,1,1,0,0,0,209,3
35530,166,12,2024,2024m12,33,5,Angra dos Reis,3300100,Interior,0,...,12.0,0.0,68,5,0,0,0,0,559,3
35531,167,12,2024,2024m12,43,5,Paraty,3303807,Interior,1,...,2.0,0.0,17,2,1,0,0,0,223,3
35532,168,12,2024,2024m12,28,5,Rio Claro,3304409,Interior,0,...,1.0,0.0,6,0,0,0,0,0,42,3

In [11]:
df_pessoas_desaparecidas_2024 = df_2024.groupby('cisp')['pessoas_desaparecidas'].sum().reset_index()
df_pessoas_desaparecidas_2024

     cisp  pessoas_desaparecidas
0       1                     14
1       4                     50
2       5                     55
3       6                     34
4       7                     18
..    ...                    ...
132   159                     17
133   165                     12
134   166                     60
135   167                     14
136   168                      4

[137 rows x 2 columns]

In [12]:
df_baixada_2020 = df.loc[(df["ano"] == 2020) & (df["regiao"] == "Baixada Fluminense")]
df_baixada_2020

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
27354,48,1,2020,2020m01,24,3,Seropédica,3305554,Baixada Fluminense,2,...,10.0,0.0,30,2,0,0,0,0,259,3
27355,50,1,2020,2020m01,24,3,Itaguaí,3302007,Baixada Fluminense,1,...,9.0,0.0,42,1,0,0,0,0,376,3
27356,51,1,2020,2020m01,24,3,Paracambi,3303609,Baixada Fluminense,0,...,6.0,0.0,16,0,0,0,0,0,116,3
27357,52,1,2020,2020m01,20,3,Nova Iguaçu,3303500,Baixada Fluminense,2,...,24.0,1.0,42,5,0,0,0,0,860,3
27358,53,1,2020,2020m01,20,3,Mesquita,3302858,Baixada Fluminense,3,...,11.0,0.0,57,7,1,0,0,0,610,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28875,63,12,2020,2020m12,24,3,Japeri,3302270,Baixada Fluminense,5,...,2.0,2.0,15,1,0,0,0,0,152,3
28876,64,12,2020,2020m12,21,3,São João de Meriti,3305109,Baixada Fluminense,13,...,8.0,0.0,85,10,0,0,0,0,1189,3
28877,65,12,2020,2020m12,34,3,Magé,3302502,Baixada Fluminense,3,...,6.0,0.0,23,1,0,0,0,0,197,3
28878,66,12,2020,2020m12,34,3,Magé,3302502,Baixada Fluminense,0,...,7.0,1.0,65,8,0,0,0,0,390,3
28879,67,12,2020,2020m12,34,3,Guapimirim,3301850,Baixada Fluminense,1,...,1.0,0.0,13,1,0,0,0,0,114,3

In [13]:
dados = np.array([12, 15, 17, 20, 22, 25, 28, 30, 35, 40])
q1 = np.percentile(dados, 25)
q2 = np.percentile(dados, 50)
q3 = np.percentile(dados, 75)
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2, mediana): {q2}')
print(f'Terceiro quartil (Q3): {q3}')

Primeiro quartil (Q1): 17.75
Segundo quartil (Q2, mediana): 23.5
Terceiro quartil (Q3): 29.5

In [23]:
array_furto_celular = np.array(df_furto_celular_cisp['furto_celular'])
q1_furto_celular = np.percentile(array_furto_celular, 25)
q2_furto_celular = np.percentile(array_furto_celular, 50)
q3_furto_celular = np.percentile(array_furto_celular, 75)
media = np.mean(array_furto_celular)
mediana = np.median(array_furto_celular)
distancia = (media - mediana) / mediana
iqr = q3_furto_celular - q1_furto_celular
limite_superior = q3_furto_celular + 1.5 * iqr
limite_inferior = q1_furto_celular - 1.5 * iqr
print(f'Primeiro quartil (Q1): {q1_furto_celular}')
print(f'Segundo quartil (Q2, mediana): {q2_furto_celular}')
print(f'Terceiro quartil (Q3): {q3_furto_celular}')
print(f'O valor da média é: {media}')
print(f'O valor da mediana é: {mediana}')
print(f'A distância entre a média e a mediana é: {distancia * 100}')
print(f'O limite superior é:{limite_superior}')
print(f'O limite inferior é:{limite_inferior}')

Primeiro quartil (Q1): 451.25
Segundo quartil (Q2, mediana): 1675.5
Terceiro quartil (Q3): 4580.0
O valor da média é: 3422.978260869565
O valor da mediana é: 1675.5
A distância entre a média e a mediana é: 104.29592723781349
O limite superior é:10773.125
O limite inferior é:-5741.875

In [24]:
outliers_cisp_furto_celular = df_furto_celular_cisp.loc[df_furto_celular_cisp['furto_celular'] >= limite_superior]

outliers_cisp_furto_celular = outliers_cisp_furto_celular.sort_values(by='furto_celular', ascending=False)

outliers_cisp_furto_celular

    cisp  furto_celular
12    16          25480
2      5          23969
10    14          17633
8     12          16659
0      1          15487
5      9          14621
6     10          14370
14    18          13808
1      4          13700
28    32          12504
31    35          12007

In [15]:
df_menor_q1_furto_celular = df_furto_celular_cisp.loc[df_furto_celular_cisp['furto_celular'] < q1_furto_celular]
df_menor_q1_furto_celular = df_menor_q1_furto_celular.sort_values(by='furto_celular')
df_menor_q1_furto_celular

     cisp  furto_celular
129   155             47
114   138             53
131   157             55
77     92             65
87    104             72
41     45             73
94    111             82
83     98             90
130   156            109
126   152            109
137   168            121
118   142            128
92    109            143
132   158            154
123   147            165
116   140            165
124   148            195
61     70            202
100   122            202
95    112            211
82     97            233
108   130            242
127   153            254
98    120            299
113   137            303
111   135            355
86    101            356
115   139            364
79     94            367
60     67            372
7      11            392
85    100            401
84     99            435
90    107            446
99    121            450

In [16]:
gestao_atual = [2023, 2024, 2025, 2026]
df_interior_atual = df.loc[(df["regiao"] == "Interior") & (df["ano"].isin(gestao_atual))]
df_interior_atual

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
32305,70,1,2023,2023m01,35,4,Tanguá,3305752,Interior,0,...,3.0,0.0,8,0,0,0,0,0,68,3
32306,71,1,2023,2023m01,35,4,Itaboraí,3301900,Interior,1,...,6.0,0.0,26,2,0,0,0,0,454,3
32317,88,1,2023,2023m01,10,5,Barra do Pirai,3300308,Interior,2,...,8.0,0.0,22,1,0,0,0,0,261,3
32318,89,1,2023,2023m01,37,5,Resende,3304201,Interior,6,...,10.0,2.0,37,4,0,0,0,0,516,3
32319,90,1,2023,2023m01,28,5,Barra Mansa,3300407,Interior,6,...,8.0,0.0,61,0,0,0,0,0,480,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,2.0,0.0,37,1,0,0,0,0,157,2
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,32,0,0,0,0,0,234,2
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,10.0,0.0,98,9,1,0,0,0,713,2
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,3.0,0.0,25,2,0,0,0,0,258,2
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0.0,0.0,3,0,0,0,0,0,57,2

In [17]:
regiao_metropolitana = [ "Belford Roxo",
 "Duque de Caxias",
 "Guapimirim",
"Itaboraí",
 "Itaguaí",
"Japerí",
 "Magé",
 "Maricá",
 "Mesquita",
" Nilópolis",
 "Niterói",
 "Nova Iguaçu",
 "Paracambi ",
 "Petrópolis",
 "Queimados",
 "Seropédica",
 "São Gonçalo",
 "São João de Merití",
 "Tanguá",
 "Cachoeiras de Macacu",
 "Rio Bonito",
 "Rio de Janeiro",
]

In [18]:
df_rm_24 = df.loc[(df["ano"] == 2024) & (df["munic"].isin(regiao_metropolitana))]

In [19]:
df_furto_cel_rm_24 = df_rm_24.groupby('cisp')['furto_celular'].sum().reset_index()

array_furto_celular = np.array(df_furto_cel_rm_24['furto_celular'])
media = np.mean(array_furto_celular)
mediana = np.median(array_furto_celular)
distancia = (media - mediana) / mediana
print(f'O valor da média é: {media}')
print(f'O valor da mediana é: {mediana}')
print(f'A distância entre a média e a mediana é: {round(distancia, 2) * 100} %')

O valor da média é: 472.72222222222223
O valor da mediana é: 230.0
A distância entre a média e a mediana é: 106.0 %

In [20]:
munic = df.groupby("munic").size().reset_index(name='Quantidade')

In [21]:
munic.to_csv("municipios.csv", index=False, sep=";")