In [1]:
import pandas as pd
import numpy as np

In [3]:
dados_1sem = "Preços semestrais - AUTOMOTIVOS_2025.01.csv"
df_1sem = pd.read_csv(dados_1sem, encoding="latin-1", sep=";")
df_1sem.head(3)

C:\Users\alex.justino\AppData\Local\Temp\ipykernel_9088\2987220498.py:2: DtypeWarning: Columns (0: ï»¿Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Valor de Venda, 13: Unidade de Medida, 14: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_1sem = pd.read_csv(dados_1sem, encoding="latin-1", sep=";")

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN

In [4]:
dados_2sem = "Preços semestrais - AUTOMOTIVOS_2025.02.csv"
df_2sem = pd.read_csv(dados_2sem, encoding="latin-1", sep=";")
df_2sem.head(3)

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,4431113000100,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,DIESEL,01/07/2025,"6,69",NaN,R$ / litro,BRANCA
1,N,AP,MACAPA,SEPE TIARAJU EMPREENDIMENTOS LTDA,5297501000286,RUA SETENTRIONAL,S/N,ESQUINA COM BEIRA RIO,ARAXÃ,68903-640,DIESEL,01/07/2025,"6,33",NaN,R$ / litro,BRANCA
2,NE,BA,IPIRA,AUTO POSTO AUGUSTU'S LTDA,2448248000145,SITIO SAO JOSE,SN,NaN,SEDE,44600-000,DIESEL,01/07/2025,"6,9",NaN,R$ / litro,ALE

In [6]:
df_2sem["CNPJ da Revenda"] = df_2sem["CNPJ da Revenda"].astype(str)

In [7]:
df_2sem.info()

<class 'pandas.DataFrame'>
RangeIndex: 384208 entries, 0 to 384207
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ï»¿Regiao - Sigla  384208 non-null  str
 1   Estado - Sigla     384208 non-null  str
 2   Municipio          384208 non-null  str
 3   Revenda            384208 non-null  str
 4   CNPJ da Revenda    384208 non-null  str
 5   Nome da Rua        384208 non-null  str
 6   Numero Rua         384184 non-null  str
 7   Complemento        86707 non-null   str
 8   Bairro             383546 non-null  str
 9   Cep                384208 non-null  str
 10  Produto            384208 non-null  str
 11  Data da Coleta     384208 non-null  str
 12  Valor de Venda     384208 non-null  str
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  384208 non-null  str
 15  Bandeira           384208 non-null  str
dtypes: float64(1), str(15)
memory usage: 46.9 MB

In [8]:
df_anp = pd.concat([df_1sem, df_2sem], ignore_index=True)

In [9]:
df_anp

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN
3,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,ETANOL,01/01/2025,"5,19",NaN,R$ / litro,RAIZEN
4,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,GASOLINA,01/01/2025,"6,53",NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813726,NE,BA,ALAGOINHAS,2 A COMERCIO DE COMBUSTIVEIS GNV E LUBRIFICANT...,14238511000150,RODOVIA BR 101 KM 116,S/N,SALA 01,CENTRO,48005-440,GNV,31/12/2025,"4,38",NaN,R$ / m3,LARCO
813727,NE,PB,BAYEUX,PETROGAS COMERCIO DE COMBUSTIVEIS LTDA,21553439000111,AVENIDA LIBERDADE,3545,ANDAR: 1; ANEXO: A;,SESI,58306-000,GNV,31/12/2025,"4,85",NaN,R$ / m3,ALE
813728,NE,BA,ILHEUS,BATISTA COMERCIO DE COMBUSTIVEIS E LUBRIFICANT...,28562491000183,AVENIDA FERROVIARIA,S/N,KM 05 RODOVIA ILHEUS,IGUAPE,45658-340,GNV,31/12/2025,"4,73",NaN,R$ / m3,BRANCA
813729,SE,SP,JACAREI,AUTO POSTO BRANCO DE CASTELO LTDA,68912864000385,AVENIDA SIQUEIRA CAMPOS,641,NaN,CENTRO,12308-190,GNV,31/12/2025,"3,99",NaN,R$ / m3,VIBRA
813730,S,RS,LAJEADO,SIM REDE DE POSTOS LTDA,7473735018714,RODOVIA ERS-130,2285,KM 72.8,SANTO ANDRE,95912-000,GNV,31/12/2025,"5,65",NaN,R$ / m3,CHARRUA