In [6]:
import pandas as pd
import numpy as np

In [7]:
dados = "https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv"

df = pd.read_csv(dados, sep= ";", encoding= "latin1")

In [5]:
df_capital = df[df['regiao'] == 'Capital']

veiculos_por_delegacia = df_capital.groupby('cisp')[['roubo_veiculo', 'furto_veiculos']].sum()

veiculos_por_delegacia['total_ocorrencias_veiculos'] = veiculos_por_delegacia['roubo_veiculo'] + veiculos_por_delegacia['furto_veiculos']

veiculos_por_delegacia_sorted = veiculos_por_delegacia.sort_values('total_ocorrencias_veiculos', ascending=False)

veiculos_por_delegacia_sorted

      roubo_veiculo  furto_veiculos  total_ocorrencias_veiculos
cisp
27            27543           11907                       39450
34            27298            9804                       37102
35            19186           14538                       33724
39            29077            3868                       32945
38            19774            6523                       26297
33            17862            8263                       26125
21            19604            5982                       25586
22            15072            8027                       23099
40            19082            3684                       22766
29            16305            5924                       22229
16             5864           12447                       18311
30            12660            5378                       18038
31            14866            3057                       17923
44            14619            2784                       17403
23            10743            4619                       15362
24            11842            3034                       14876
28            10939            3585                       14524
32             8412            5787                       14199
20             9023            4335                       13358
37             7355            5646                       13001
9              4669            8160                       12829
25            10952            1868                       12820
17             7662            3769                       11431
18             7269            4122                       11391
26             7714            2839                       10553
19             6844            3493                       10337
42             3659            6632                       10291
41             6391            3888                       10279
36             5168            4992                       10160
10             2937            6828                        9765
6              4621            2270                        6891
43             2087            2407                        4494
5              1362            3052                        4414
7              2013            1968                        3981
14             1058            2541                        3599
4              2196            1248                        3444
15             1250            1876                        3126
1               572            1938                        2510
12              321            2147                        2468
13              311            1217                        1528
11               17             168                         185
45               27              51                          78

In [8]:
max_ano = max(df['ano'])

df_decada = df.loc[df['ano'] >= (max_ano - 10)]

df_decada

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
20701,1,1,2016,2016m01,5,1,Rio de Janeiro,3304557,Capital,0,...,2.0,3.0,15,0,0,0,0,0,411,3
20702,4,1,2016,2016m01,5,1,Rio de Janeiro,3304557,Capital,0,...,3.0,1.0,20,4,1,0,0,0,1054,3
20703,5,1,2016,2016m01,5,1,Rio de Janeiro,3304557,Capital,0,...,27.0,6.0,32,6,0,0,0,0,1274,3
20704,6,1,2016,2016m01,4,1,Rio de Janeiro,3304557,Capital,0,...,22.0,0.0,26,3,0,0,0,0,595,3
20705,7,1,2016,2016m01,5,1,Rio de Janeiro,3304557,Capital,3,...,1.0,0.0,12,3,0,0,0,0,224,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,2.0,0.0,37,1,0,0,0,0,157,2
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,32,0,0,0,0,0,234,2
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,10.0,0.0,98,9,1,0,0,0,713,2
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,3.0,0.0,25,2,0,0,0,0,258,2
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0.0,0.0,3,0,0,0,0,0,57,2

In [10]:
max_ano = max(df['ano'])

df_decada = df.loc[df['ano'] >= (max_ano - 10)]

df_capital = df[df['regiao'] == 'Capital']

veiculos_por_delegacia = df_capital.groupby('cisp')[['furto_veiculos']].sum()

veiculos_por_delegacia['total_ocorrencias_veiculos'] = veiculos_por_delegacia['furto_veiculos']

veiculos_por_delegacia_sorted = veiculos_por_delegacia.sort_values('total_ocorrencias_veiculos', ascending=False)

veiculos_por_delegacia_sorted

      furto_veiculos  total_ocorrencias_veiculos
cisp
35             14538                       14538
16             12447                       12447
27             11907                       11907
34              9804                        9804
33              8263                        8263
9               8160                        8160
22              8027                        8027
10              6828                        6828
42              6632                        6632
38              6523                        6523
21              5982                        5982
29              5924                        5924
32              5787                        5787
37              5646                        5646
30              5378                        5378
36              4992                        4992
23              4619                        4619
20              4335                        4335
18              4122                        4122
41              3888                        3888
39              3868                        3868
17              3769                        3769
40              3684                        3684
28              3585                        3585
19              3493                        3493
31              3057                        3057
5               3052                        3052
24              3034                        3034
26              2839                        2839
44              2784                        2784
14              2541                        2541
43              2407                        2407
6               2270                        2270
12              2147                        2147
7               1968                        1968
1               1938                        1938
15              1876                        1876
25              1868                        1868
4               1248                        1248
13              1217                        1217
11               168                         168
45                51                          51